first workflow

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -7,3 +7,13 @@ jobs:
       steps:
         - name: Say hello
           run: echo "hello world"
+    
+    echo-goodbye:
+      runs-on: ubuntu-latest
+      steps:
+        - name: failed step
+          run: |
+            echo "I will fail"
+            exit 1
+        - name: good bye
+          run: echo "good bye"
